/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import static myapp.DetailBookService.orderList;

/**
 *
 * @author I3
 */
public class AllBook extends javax.swing.JPanel {

    int index = 1;
     ArrayList<Books> bookAll;
    OrderCart Order;
    /**
     * Creates new form BookAll
     */
    public AllBook() {
        initComponents();
        showAllBook();
    }

     public  void showAllBook(){
         bookAll = AllBookService.getAllBook();
         if(bookAll!=null){
             loopForShowBook(true);
        }
     }
     
     public  void loopForShowBook(boolean next){
                 int count = 1;
                 if(next==false && index==10){
                     index = index-10;
                 }else if(next==false && index-20>=0){
                    index = index-20;
                 }else if(next==false){
                     return;
                 }
             for(Books book:bookAll.subList(index,bookAll.size()-1)){
                loadDetail(count,book);
                if(count>9){
                    break;
                }               
                index++;
                count++;
                
             
             }
     }
     
             
     public void loadDetail(int count,Books book){
         try{
         BufferedImage imgBuffer = BookDAO.getImageBook(book.bookname);
         Image rescale = imgBuffer.getScaledInstance(150, 210, Image.SCALE_DEFAULT);  
           
          if(count==1){
              lblShowBook1.setIcon(new ImageIcon(rescale));
              lblBookName1.setText("ชื่อ "+book.bookname);
              lblBookPrice1.setText("ราคา "+Integer.toString(book.bookprice));
              
           }else if(count==2){
               lblShowBook2.setIcon(new ImageIcon(rescale));
              lblBookName2.setText("ชื่อ "+book.bookname);
                lblBookPrice2.setText("ราคา "+Integer.toString(book.bookprice));
              
           }else if(count==3){
               lblShowBook3.setIcon(new ImageIcon(rescale));
              lblBookName3.setText("ชื่อ "+book.bookname);
                lblBookPrice3.setText("ราคา "+Integer.toString(book.bookprice));
              
           }else if(count==4){
               lblShowBook4.setIcon(new ImageIcon(rescale));
              lblBookName4.setText("ชื่อ "+book.bookname);
                lblBookPrice4.setText("ราคา "+Integer.toString(book.bookprice));
               
           }else if(count==5){
               lblShowBook5.setIcon(new ImageIcon(rescale));
              lblBookName5.setText("ชื่อ "+book.bookname);
                lblBookPrice5.setText("ราคา "+Integer.toString(book.bookprice));
              
           }else if(count==6){
               lblShowBook6.setIcon(new ImageIcon(rescale));
                lblBookName6.setText("ชื่อ "+book.bookname);    
                lblBookPrice6.setText("ราคา "+Integer.toString(book.bookprice));
              
           }else if(count==7){
               lblShowBook7.setIcon(new ImageIcon(rescale));
              lblBookName7.setText("ชื่อ "+book.bookname);
                lblBookPrice7.setText("ราคา "+Integer.toString(book.bookprice));
              
           }else if(count==8){
               lblShowBook8.setIcon(new ImageIcon(rescale));
              lblBookName8.setText("ชื่อ "+book.bookname);
                lblBookPrice8.setText("ราคา "+Integer.toString(book.bookprice));
               
           }else if(count==9){
               lblShowBook9.setIcon(new ImageIcon(rescale));
             lblBookName9.setText("ชื่อ "+book.bookname);
                lblBookPrice9.setText("ราคา "+Integer.toString(book.bookprice));
              
           }else if(count==10){
               lblShowBook10.setIcon(new ImageIcon(rescale));
             lblBookName10.setText("ชื่อ "+book.bookname);
                lblBookPrice10.setText("ราคา "+Integer.toString(book.bookprice));
               
           } }catch (IOException ex) {
           
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAllBook = new javax.swing.JPanel();
        panelMenuBar = new javax.swing.JPanel();
        lblUserStatus = new javax.swing.JLabel();
        panelMenuBar1 = new javax.swing.JPanel();
        btnAllBook = new javax.swing.JButton();
        btnCart = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        imgCustCare = new javax.swing.JLabel();
        lblBookDetail = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelShowAllBook = new javax.swing.JPanel();
        btnSelect1 = new javax.swing.JButton();
        lblBookPrice1 = new javax.swing.JLabel();
        lblBookName1 = new javax.swing.JLabel();
        lblShowBook1 = new javax.swing.JLabel();
        lblShowBook2 = new javax.swing.JLabel();
        lblBookName2 = new javax.swing.JLabel();
        lblBookPrice2 = new javax.swing.JLabel();
        btnSelect2 = new javax.swing.JButton();
        btnSelect3 = new javax.swing.JButton();
        lblBookPrice3 = new javax.swing.JLabel();
        lblBookName3 = new javax.swing.JLabel();
        lblShowBook3 = new javax.swing.JLabel();
        lblShowBook4 = new javax.swing.JLabel();
        lblShowBook5 = new javax.swing.JLabel();
        lblBookName4 = new javax.swing.JLabel();
        lblBookName5 = new javax.swing.JLabel();
        lblBookPrice5 = new javax.swing.JLabel();
        lblBookPrice4 = new javax.swing.JLabel();
        btnSelect4 = new javax.swing.JButton();
        btnSelect5 = new javax.swing.JButton();
        btnSelect6 = new javax.swing.JButton();
        lblBookPrice6 = new javax.swing.JLabel();
        lblBookName6 = new javax.swing.JLabel();
        lblShowBook6 = new javax.swing.JLabel();
        lblShowBook7 = new javax.swing.JLabel();
        lblBookName7 = new javax.swing.JLabel();
        lblBookPrice7 = new javax.swing.JLabel();
        btnSelect7 = new javax.swing.JButton();
        btnSelect8 = new javax.swing.JButton();
        lblBookPrice8 = new javax.swing.JLabel();
        lblBookName8 = new javax.swing.JLabel();
        lblShowBook8 = new javax.swing.JLabel();
        lblShowBook9 = new javax.swing.JLabel();
        lblShowBook10 = new javax.swing.JLabel();
        lblBookName9 = new javax.swing.JLabel();
        lblBookName10 = new javax.swing.JLabel();
        lblBookPrice10 = new javax.swing.JLabel();
        lblBookPrice9 = new javax.swing.JLabel();
        btnSelect9 = new javax.swing.JButton();
        btnSelect10 = new javax.swing.JButton();
        lblAllBook = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblNext = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAllBook.setBackground(new java.awt.Color(255, 255, 255));
        panelAllBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenuBar.setBackground(new java.awt.Color(255, 255, 255));
        panelMenuBar.setName(""); // NOI18N
        panelMenuBar.setPreferredSize(new java.awt.Dimension(1024, 60));
        panelMenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserStatus.setBackground(new java.awt.Color(255, 255, 255));
        lblUserStatus.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblUserStatus.setForeground(new java.awt.Color(204, 204, 255));
        lblUserStatus.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUserStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgUser.png"))); // NOI18N
        lblUserStatus.setText("mamafakka");
        panelMenuBar.add(lblUserStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 220, 40));

        panelMenuBar1.setBackground(new java.awt.Color(204, 204, 255));
        panelMenuBar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAllBook.setBackground(new java.awt.Color(204, 204, 255));
        btnAllBook.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnAllBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgAllbook1.png"))); // NOI18N
        btnAllBook.setText("หนังสือทั้งหมด");
        btnAllBook.setBorder(null);
        btnAllBook.setBorderPainted(false);
        btnAllBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAllBook.setFocusable(false);
        btnAllBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllBookActionPerformed(evt);
            }
        });
        panelMenuBar1.add(btnAllBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 160, 40));

        btnCart.setBackground(new java.awt.Color(204, 204, 255));
        btnCart.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgShoppingCart.png"))); // NOI18N
        btnCart.setBorder(null);
        btnCart.setBorderPainted(false);
        btnCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCart.setFocusable(false);
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });
        panelMenuBar1.add(btnCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 80, 40));

        panelMenuBar.add(panelMenuBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1080, 40));

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgLogo2.png"))); // NOI18N
        panelMenuBar.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 270, 60));

        imgCustCare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgContact.png"))); // NOI18N
        panelMenuBar.add(imgCustCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 230, 60));

        panelAllBook.add(panelMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 99));

        lblBookDetail.setBackground(new java.awt.Color(255, 255, 255));
        lblBookDetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelAllBook.add(lblBookDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelShowAllBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSelect1.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnSelect1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgMagnifyingGlass.png"))); // NOI18N
        btnSelect1.setText("เลือกดู");
        btnSelect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect1ActionPerformed(evt);
            }
        });
        panelShowAllBook.add(btnSelect1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 110, 40));

        lblBookPrice1.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookPrice1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookPrice1.setText("ราคา :");
        panelShowAllBook.add(lblBookPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 30));

        lblBookName1.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookName1.setText("ชื่อหนังสือ");
        panelShowAllBook.add(lblBookName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 30));

        lblShowBook1.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblShowBook1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowBook1.setText("ปกหนังสือที่ 1");
        panelShowAllBook.add(lblShowBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 210));

        lblShowBook2.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblShowBook2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowBook2.setText("ปกหนังสือที่ 2");
        panelShowAllBook.add(lblShowBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 210));

        lblBookName2.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookName2.setText("ชื่อหนังสือ");
        panelShowAllBook.add(lblBookName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 150, 30));

        lblBookPrice2.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookPrice2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookPrice2.setText("ราคา :");
        panelShowAllBook.add(lblBookPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 150, 30));

        btnSelect2.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnSelect2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgMagnifyingGlass.png"))); // NOI18N
        btnSelect2.setText("เลือกดู");
        btnSelect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect2ActionPerformed(evt);
            }
        });
        panelShowAllBook.add(btnSelect2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 110, 40));

        btnSelect3.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnSelect3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgMagnifyingGlass.png"))); // NOI18N
        btnSelect3.setText("เลือกดู");
        btnSelect3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect3ActionPerformed(evt);
            }
        });
        panelShowAllBook.add(btnSelect3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 110, 40));

        lblBookPrice3.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookPrice3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookPrice3.setText("ราคา :");
        panelShowAllBook.add(lblBookPrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 150, 30));

        lblBookName3.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookName3.setText("ชื่อหนังสือ");
        panelShowAllBook.add(lblBookName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 150, 30));

        lblShowBook3.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblShowBook3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowBook3.setText("ปกหนังสือที่ 3");
        panelShowAllBook.add(lblShowBook3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 150, 210));

        lblShowBook4.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblShowBook4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowBook4.setText("ปกหนังสือที่ 4");
        panelShowAllBook.add(lblShowBook4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 150, 210));

        lblShowBook5.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblShowBook5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowBook5.setText("ปกหนังสือที่ 5");
        panelShowAllBook.add(lblShowBook5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 150, 210));

        lblBookName4.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookName4.setText("ชื่อหนังสือ");
        panelShowAllBook.add(lblBookName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 150, 30));

        lblBookName5.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookName5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookName5.setText("ชื่อหนังสือ");
        panelShowAllBook.add(lblBookName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 150, 30));

        lblBookPrice5.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookPrice5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookPrice5.setText("ราคา :");
        panelShowAllBook.add(lblBookPrice5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 150, 30));

        lblBookPrice4.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookPrice4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookPrice4.setText("ราคา :");
        panelShowAllBook.add(lblBookPrice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 150, 30));

        btnSelect4.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnSelect4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgMagnifyingGlass.png"))); // NOI18N
        btnSelect4.setText("เลือกดู");
        btnSelect4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect4ActionPerformed(evt);
            }
        });
        panelShowAllBook.add(btnSelect4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 110, 40));

        btnSelect5.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnSelect5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgMagnifyingGlass.png"))); // NOI18N
        btnSelect5.setText("เลือกดู");
        btnSelect5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect5ActionPerformed(evt);
            }
        });
        panelShowAllBook.add(btnSelect5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 110, 40));

        btnSelect6.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnSelect6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgMagnifyingGlass.png"))); // NOI18N
        btnSelect6.setText("เลือกดู");
        btnSelect6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect6ActionPerformed(evt);
            }
        });
        panelShowAllBook.add(btnSelect6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 110, 40));

        lblBookPrice6.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookPrice6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookPrice6.setText("ราคา :");
        panelShowAllBook.add(lblBookPrice6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 150, 30));

        lblBookName6.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookName6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookName6.setText("ชื่อหนังสือ");
        panelShowAllBook.add(lblBookName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 150, 30));

        lblShowBook6.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblShowBook6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowBook6.setText("ปกหนังสือที่ 6");
        panelShowAllBook.add(lblShowBook6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 150, 210));

        lblShowBook7.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblShowBook7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowBook7.setText("ปกหนังสือที่ 7");
        panelShowAllBook.add(lblShowBook7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 150, 210));

        lblBookName7.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookName7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookName7.setText("ชื่อหนังสือ");
        panelShowAllBook.add(lblBookName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 150, 30));

        lblBookPrice7.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookPrice7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookPrice7.setText("ราคา :");
        panelShowAllBook.add(lblBookPrice7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 150, 30));

        btnSelect7.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnSelect7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgMagnifyingGlass.png"))); // NOI18N
        btnSelect7.setText("เลือกดู");
        btnSelect7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect7ActionPerformed(evt);
            }
        });
        panelShowAllBook.add(btnSelect7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 700, 110, 40));

        btnSelect8.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnSelect8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgMagnifyingGlass.png"))); // NOI18N
        btnSelect8.setText("เลือกดู");
        btnSelect8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect8ActionPerformed(evt);
            }
        });
        panelShowAllBook.add(btnSelect8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 700, 110, 40));

        lblBookPrice8.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookPrice8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookPrice8.setText("ราคา :");
        panelShowAllBook.add(lblBookPrice8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 660, 150, 30));

        lblBookName8.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookName8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookName8.setText("ชื่อหนังสือ");
        panelShowAllBook.add(lblBookName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 150, 30));

        lblShowBook8.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblShowBook8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowBook8.setText("ปกหนังสือที่ 8");
        panelShowAllBook.add(lblShowBook8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 150, 210));

        lblShowBook9.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblShowBook9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowBook9.setText("ปกหนังสือที่ 9");
        panelShowAllBook.add(lblShowBook9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 150, 210));

        lblShowBook10.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblShowBook10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowBook10.setText("ปกหนังสือที่ 10");
        panelShowAllBook.add(lblShowBook10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 150, 210));

        lblBookName9.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookName9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookName9.setText("ชื่อหนังสือ");
        panelShowAllBook.add(lblBookName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, 150, 30));

        lblBookName10.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookName10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookName10.setText("ชื่อหนังสือ");
        panelShowAllBook.add(lblBookName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, 150, 30));

        lblBookPrice10.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookPrice10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookPrice10.setText("ราคา :");
        panelShowAllBook.add(lblBookPrice10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 660, 150, 30));

        lblBookPrice9.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        lblBookPrice9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBookPrice9.setText("ราคา :");
        panelShowAllBook.add(lblBookPrice9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 660, 150, 30));

        btnSelect9.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnSelect9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgMagnifyingGlass.png"))); // NOI18N
        btnSelect9.setText("เลือกดู");
        btnSelect9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect9ActionPerformed(evt);
            }
        });
        panelShowAllBook.add(btnSelect9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 700, 110, 40));

        btnSelect10.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btnSelect10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgMagnifyingGlass.png"))); // NOI18N
        btnSelect10.setText("เลือกดู");
        btnSelect10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelect10ActionPerformed(evt);
            }
        });
        panelShowAllBook.add(btnSelect10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 700, 110, 40));

        jScrollPane2.setViewportView(panelShowAllBook);

        panelAllBook.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 900, 350));

        lblAllBook.setFont(new java.awt.Font("Ekkamai Standard", 1, 24)); // NOI18N
        lblAllBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgAllbook2.png"))); // NOI18N
        lblAllBook.setText("หนังสือทั้งหมด");
        panelAllBook.add(lblAllBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 220, 50));

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgBackButton.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });
        panelAllBook.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        lblNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgNextButton.png"))); // NOI18N
        lblNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNextMouseClicked(evt);
            }
        });
        panelAllBook.add(lblNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, -1, -1));

        add(panelAllBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect1ActionPerformed
        // TODO add your handling code here:
        String[] partsName = lblBookName1.getText().split(" ");
        String nameBook = partsName[1]; 
       AllBookService.toDetailBook(nameBook);
    }//GEN-LAST:event_btnSelect1ActionPerformed

    private void btnSelect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect2ActionPerformed
        // TODO add your handling code here:
       String[] partsName = lblBookName2.getText().split(" ");
        String nameBook = partsName[1]; 
       AllBookService.toDetailBook(nameBook);
    }//GEN-LAST:event_btnSelect2ActionPerformed

    private void btnSelect3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect3ActionPerformed
        // TODO add your handling code here:
       String[] partsName = lblBookName3.getText().split(" ");
        String nameBook = partsName[1]; 
       AllBookService.toDetailBook(nameBook);
    }//GEN-LAST:event_btnSelect3ActionPerformed

    private void btnSelect4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect4ActionPerformed
        // TODO add your handling code here:
       String[] partsName = lblBookName4.getText().split(" ");
        String nameBook = partsName[1]; 
       AllBookService.toDetailBook(nameBook);
    }//GEN-LAST:event_btnSelect4ActionPerformed

    private void btnSelect5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect5ActionPerformed
        // TODO add your handling code here:
        String[] partsName = lblBookName5.getText().split(" ");
        String nameBook = partsName[1]; 
       AllBookService.toDetailBook(nameBook);
    }//GEN-LAST:event_btnSelect5ActionPerformed

    private void btnSelect6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect6ActionPerformed
        String[] partsName = lblBookName6.getText().split(" ");
        String nameBook = partsName[1]; 
       AllBookService.toDetailBook(nameBook);
    }//GEN-LAST:event_btnSelect6ActionPerformed

    private void btnSelect7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect7ActionPerformed
        // TODO add your handling code here:
        String[] partsName = lblBookName7.getText().split(" ");
        String nameBook = partsName[1]; 
       AllBookService.toDetailBook(nameBook);
    }//GEN-LAST:event_btnSelect7ActionPerformed

    private void btnSelect8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect8ActionPerformed
        // TODO add your handling code here:
       String[] partsName = lblBookName8.getText().split(" ");
        String nameBook = partsName[1]; 
       AllBookService.toDetailBook(nameBook);
    }//GEN-LAST:event_btnSelect8ActionPerformed

    private void btnSelect9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect9ActionPerformed
        // TODO add your handling code here:
       String[] partsName = lblBookName9.getText().split(" ");
        String nameBook = partsName[1]; 
       AllBookService.toDetailBook(nameBook);
        
    }//GEN-LAST:event_btnSelect9ActionPerformed

    private void btnSelect10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelect10ActionPerformed
        // TODO add your handling code here:
       String[] partsName = lblBookName10.getText().split(" ");
        String nameBook = partsName[1]; 
       AllBookService.toDetailBook(nameBook);
        
    }//GEN-LAST:event_btnSelect10ActionPerformed

    private void lblNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNextMouseClicked
        loopForShowBook(true);
    }//GEN-LAST:event_lblNextMouseClicked

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        loopForShowBook(false);
    }//GEN-LAST:event_lblBackMouseClicked

    private void btnAllBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAllBookActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        
         DetailOrder form = new DetailOrder();
         form.showOrderDetail(Order);
         Main.setFrame(form);
    }//GEN-LAST:event_btnCartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllBook;
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnSelect1;
    private javax.swing.JButton btnSelect10;
    private javax.swing.JButton btnSelect2;
    private javax.swing.JButton btnSelect3;
    private javax.swing.JButton btnSelect4;
    private javax.swing.JButton btnSelect5;
    private javax.swing.JButton btnSelect6;
    private javax.swing.JButton btnSelect7;
    private javax.swing.JButton btnSelect8;
    private javax.swing.JButton btnSelect9;
    private javax.swing.JLabel imgCustCare;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAllBook;
    private javax.swing.JLabel lblBack;
    private javax.swing.JPanel lblBookDetail;
    private javax.swing.JLabel lblBookName1;
    private javax.swing.JLabel lblBookName10;
    private javax.swing.JLabel lblBookName2;
    private javax.swing.JLabel lblBookName3;
    private javax.swing.JLabel lblBookName4;
    private javax.swing.JLabel lblBookName5;
    private javax.swing.JLabel lblBookName6;
    private javax.swing.JLabel lblBookName7;
    private javax.swing.JLabel lblBookName8;
    private javax.swing.JLabel lblBookName9;
    private javax.swing.JLabel lblBookPrice1;
    private javax.swing.JLabel lblBookPrice10;
    private javax.swing.JLabel lblBookPrice2;
    private javax.swing.JLabel lblBookPrice3;
    private javax.swing.JLabel lblBookPrice4;
    private javax.swing.JLabel lblBookPrice5;
    private javax.swing.JLabel lblBookPrice6;
    private javax.swing.JLabel lblBookPrice7;
    private javax.swing.JLabel lblBookPrice8;
    private javax.swing.JLabel lblBookPrice9;
    private javax.swing.JLabel lblNext;
    private javax.swing.JLabel lblShowBook1;
    private javax.swing.JLabel lblShowBook10;
    private javax.swing.JLabel lblShowBook2;
    private javax.swing.JLabel lblShowBook3;
    private javax.swing.JLabel lblShowBook4;
    private javax.swing.JLabel lblShowBook5;
    private javax.swing.JLabel lblShowBook6;
    private javax.swing.JLabel lblShowBook7;
    private javax.swing.JLabel lblShowBook8;
    private javax.swing.JLabel lblShowBook9;
    private javax.swing.JLabel lblUserStatus;
    private javax.swing.JPanel panelAllBook;
    private javax.swing.JPanel panelMenuBar;
    private javax.swing.JPanel panelMenuBar1;
    private javax.swing.JPanel panelShowAllBook;
    // End of variables declaration//GEN-END:variables
}
