/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import java.util.ArrayList;

/**
 *
 * @author I3
 */
public class BookAll extends javax.swing.JPanel {

    /**
     * Creates new form BookAll
     */
    public BookAll() {
        initComponents();
//        setAllBook();
    }

     public  void setAllBook(){
         ArrayList<Books> bookall = BookAllService.getAllBook();
         int i = 0;
         if(bookall!=null){
             for( Books books:bookall){
                txt_nameBook1.setText("ชื่อ "+books.bookname);
                txt_priceBook1.setText("ราคา "+Double.toString(books.bookprice));
             }
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBookAll = new javax.swing.JPanel();
        statusbar1 = new javax.swing.JPanel();
        lbl_version1 = new javax.swing.JLabel();
        lbl_statusbar1 = new javax.swing.JLabel();
        panelMenu1 = new javax.swing.JPanel();
        btn_userStatus1 = new javax.swing.JLabel();
        btn_menubar1 = new javax.swing.JPanel();
        btn_allBooks = new javax.swing.JButton();
        btn_home1 = new javax.swing.JButton();
        btn_loginStatus1 = new javax.swing.JButton();
        btn_basket1 = new javax.swing.JButton();
        btn_search1 = new javax.swing.JTextField();
        btn_search_icon1 = new javax.swing.JButton();
        icon1 = new javax.swing.JLabel();
        btn_editbook1 = new javax.swing.JButton();
        img_logo1 = new javax.swing.JLabel();
        img_customercare1 = new javax.swing.JLabel();
        lbl_bookdetail = new javax.swing.JPanel();
        btn_showList = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel_AllBooks = new javax.swing.JPanel();
        btn_select1 = new javax.swing.JButton();
        txt_priceBook1 = new javax.swing.JLabel();
        txt_nameBook1 = new javax.swing.JLabel();
        lbl_showBook1 = new javax.swing.JLabel();
        lbl_showBook2 = new javax.swing.JLabel();
        txt_nameBook2 = new javax.swing.JLabel();
        txt_priceBook2 = new javax.swing.JLabel();
        btn_select2 = new javax.swing.JButton();
        btn_select3 = new javax.swing.JButton();
        txt_priceBook3 = new javax.swing.JLabel();
        txt_nameBook3 = new javax.swing.JLabel();
        lbl_showBook3 = new javax.swing.JLabel();
        lbl_showBook4 = new javax.swing.JLabel();
        lbl_showBook5 = new javax.swing.JLabel();
        txt_nameBook4 = new javax.swing.JLabel();
        txt_nameBook5 = new javax.swing.JLabel();
        txt_priceBook5 = new javax.swing.JLabel();
        txt_priceBook4 = new javax.swing.JLabel();
        btn_select4 = new javax.swing.JButton();
        btn_select5 = new javax.swing.JButton();
        btn_select6 = new javax.swing.JButton();
        txt_priceBook6 = new javax.swing.JLabel();
        txt_nameBook6 = new javax.swing.JLabel();
        lbl_showBook6 = new javax.swing.JLabel();
        lbl_showBook7 = new javax.swing.JLabel();
        txt_nameBook7 = new javax.swing.JLabel();
        txt_priceBook7 = new javax.swing.JLabel();
        btn_select7 = new javax.swing.JButton();
        btn_select8 = new javax.swing.JButton();
        txt_priceBook8 = new javax.swing.JLabel();
        txt_nameBook8 = new javax.swing.JLabel();
        lbl_showBook8 = new javax.swing.JLabel();
        lbl_showBook9 = new javax.swing.JLabel();
        lbl_showBook10 = new javax.swing.JLabel();
        txt_nameBook9 = new javax.swing.JLabel();
        txt_nameBook10 = new javax.swing.JLabel();
        txt_priceBook10 = new javax.swing.JLabel();
        txt_priceBook9 = new javax.swing.JLabel();
        btn_select9 = new javax.swing.JButton();
        btn_select10 = new javax.swing.JButton();
        lbl_AllBooks = new javax.swing.JLabel();
        btn_back = new javax.swing.JLabel();
        btn_next = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBookAll.setBackground(new java.awt.Color(255, 255, 255));
        panelBookAll.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        statusbar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_version1.setText("Version : 5.10.12.2");
        statusbar1.add(lbl_version1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        lbl_statusbar1.setText("Status : Online");
        statusbar1.add(lbl_statusbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        panelBookAll.add(statusbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 1070, 20));

        panelMenu1.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu1.setName(""); // NOI18N
        panelMenu1.setPreferredSize(new java.awt.Dimension(1024, 60));
        panelMenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_userStatus1.setBackground(new java.awt.Color(255, 255, 255));
        btn_userStatus1.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_userStatus1.setForeground(new java.awt.Color(204, 204, 255));
        btn_userStatus1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btn_userStatus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_loginuser.png"))); // NOI18N
        btn_userStatus1.setText("ผู้เยี่ยมชม");
        panelMenu1.add(btn_userStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 220, 40));

        btn_menubar1.setBackground(new java.awt.Color(204, 204, 255));
        btn_menubar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_allBooks.setBackground(new java.awt.Color(204, 204, 255));
        btn_allBooks.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_allBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_allbook_26px.png"))); // NOI18N
        btn_allBooks.setText("หนังสือทั้งหมด");
        btn_allBooks.setBorder(null);
        btn_allBooks.setBorderPainted(false);
        btn_allBooks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_allBooks.setFocusable(false);
        btn_menubar1.add(btn_allBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 160, 40));

        btn_home1.setBackground(new java.awt.Color(204, 204, 255));
        btn_home1.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_home1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_home.png"))); // NOI18N
        btn_home1.setText("หน้าหลัก");
        btn_home1.setBorder(null);
        btn_home1.setBorderPainted(false);
        btn_home1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_home1.setFocusable(false);
        btn_menubar1.add(btn_home1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 130, 40));

        btn_loginStatus1.setBackground(new java.awt.Color(204, 204, 255));
        btn_loginStatus1.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_loginStatus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_loginuser.png"))); // NOI18N
        btn_loginStatus1.setText("เข้าสู่ระบบ");
        btn_loginStatus1.setBorder(null);
        btn_loginStatus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_loginStatus1.setFocusable(false);
        btn_menubar1.add(btn_loginStatus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 130, 40));

        btn_basket1.setBackground(new java.awt.Color(204, 204, 255));
        btn_basket1.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_basket1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_cart.png"))); // NOI18N
        btn_basket1.setText("0");
        btn_basket1.setBorder(null);
        btn_basket1.setBorderPainted(false);
        btn_basket1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_basket1.setFocusable(false);
        btn_menubar1.add(btn_basket1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 80, 40));

        btn_search1.setBackground(new java.awt.Color(205, 205, 240));
        btn_search1.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_search1.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        btn_search1.setText("กรอกเพื่อค้นหา");
        btn_search1.setBorder(null);
        btn_search1.setCaretColor(new java.awt.Color(255, 255, 255));
        btn_search1.setRequestFocusEnabled(false);
        btn_search1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        btn_search1.setSelectionColor(new java.awt.Color(255, 255, 255));
        btn_search1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_search1MouseClicked(evt);
            }
        });
        btn_menubar1.add(btn_search1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 100, 40));

        btn_search_icon1.setBackground(new java.awt.Color(205, 205, 240));
        btn_search_icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_search.png"))); // NOI18N
        btn_search_icon1.setBorder(null);
        btn_search_icon1.setBorderPainted(false);
        btn_search_icon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_search_icon1.setFocusable(false);
        btn_menubar1.add(btn_search_icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 0, 40, 40));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_searchbar.png"))); // NOI18N
        btn_menubar1.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 5, 30, 30));

        btn_editbook1.setBackground(new java.awt.Color(204, 204, 255));
        btn_editbook1.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_editbook1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_edit.png"))); // NOI18N
        btn_editbook1.setText("แก้ไขหนังสือ");
        btn_editbook1.setBorder(null);
        btn_editbook1.setBorderPainted(false);
        btn_editbook1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editbook1.setFocusable(false);
        btn_menubar1.add(btn_editbook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 140, 40));

        panelMenu1.add(btn_menubar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1080, 40));

        img_logo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        panelMenu1.add(img_logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 60));

        img_customercare1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_contactcare.png"))); // NOI18N
        panelMenu1.add(img_customercare1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 230, 60));

        panelBookAll.add(panelMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 99));

        lbl_bookdetail.setBackground(new java.awt.Color(255, 255, 255));
        lbl_bookdetail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelBookAll.add(lbl_bookdetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn_showList.setFont(new java.awt.Font("Ekkamai Standard", 0, 15)); // NOI18N
        btn_showList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_allbooklist.png"))); // NOI18N
        btn_showList.setText("แสดงแบบ List");
        btn_showList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showListActionPerformed(evt);
            }
        });
        panelBookAll.add(btn_showList, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 120, 150, 40));

        panel_AllBooks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_select1.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_select1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_browse.png"))); // NOI18N
        btn_select1.setText("เลือกดู");
        btn_select1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select1ActionPerformed(evt);
            }
        });
        panel_AllBooks.add(btn_select1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 110, 40));

        txt_priceBook1.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_priceBook1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_priceBook1.setText("ราคา :");
        panel_AllBooks.add(txt_priceBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 30));

        txt_nameBook1.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_nameBook1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nameBook1.setText("ชื่อหนังสือ");
        panel_AllBooks.add(txt_nameBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 150, 30));

        lbl_showBook1.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lbl_showBook1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showBook1.setText("ปกหนังสือที่ ");
        panel_AllBooks.add(lbl_showBook1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 210));

        lbl_showBook2.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lbl_showBook2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showBook2.setText("ปกหนังสือที่ 2");
        panel_AllBooks.add(lbl_showBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 150, 210));

        txt_nameBook2.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_nameBook2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nameBook2.setText("ชื่อหนังสือ");
        panel_AllBooks.add(txt_nameBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 150, 30));

        txt_priceBook2.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_priceBook2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_priceBook2.setText("ราคา :");
        panel_AllBooks.add(txt_priceBook2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 150, 30));

        btn_select2.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_select2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_browse.png"))); // NOI18N
        btn_select2.setText("เลือกดู");
        btn_select2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select2ActionPerformed(evt);
            }
        });
        panel_AllBooks.add(btn_select2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 110, 40));

        btn_select3.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_select3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_browse.png"))); // NOI18N
        btn_select3.setText("เลือกดู");
        btn_select3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select3ActionPerformed(evt);
            }
        });
        panel_AllBooks.add(btn_select3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, 110, 40));

        txt_priceBook3.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_priceBook3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_priceBook3.setText("ราคา :");
        panel_AllBooks.add(txt_priceBook3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 150, 30));

        txt_nameBook3.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_nameBook3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nameBook3.setText("ชื่อหนังสือ");
        panel_AllBooks.add(txt_nameBook3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 150, 30));

        lbl_showBook3.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lbl_showBook3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showBook3.setText("ปกหนังสือที่ 3");
        panel_AllBooks.add(lbl_showBook3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 150, 210));

        lbl_showBook4.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lbl_showBook4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showBook4.setText("ปกหนังสือที่ 4");
        panel_AllBooks.add(lbl_showBook4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 150, 210));

        lbl_showBook5.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lbl_showBook5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showBook5.setText("ปกหนังสือที่ 5");
        panel_AllBooks.add(lbl_showBook5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 150, 210));

        txt_nameBook4.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_nameBook4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nameBook4.setText("ชื่อหนังสือ");
        panel_AllBooks.add(txt_nameBook4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 150, 30));

        txt_nameBook5.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_nameBook5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nameBook5.setText("ชื่อหนังสือ");
        panel_AllBooks.add(txt_nameBook5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 150, 30));

        txt_priceBook5.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_priceBook5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_priceBook5.setText("ราคา :");
        panel_AllBooks.add(txt_priceBook5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 150, 30));

        txt_priceBook4.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_priceBook4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_priceBook4.setText("ราคา :");
        panel_AllBooks.add(txt_priceBook4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 150, 30));

        btn_select4.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_select4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_browse.png"))); // NOI18N
        btn_select4.setText("เลือกดู");
        btn_select4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select4ActionPerformed(evt);
            }
        });
        panel_AllBooks.add(btn_select4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 110, 40));

        btn_select5.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_select5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_browse.png"))); // NOI18N
        btn_select5.setText("เลือกดู");
        btn_select5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select5ActionPerformed(evt);
            }
        });
        panel_AllBooks.add(btn_select5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 110, 40));

        btn_select6.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_select6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_browse.png"))); // NOI18N
        btn_select6.setText("เลือกดู");
        btn_select6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select6ActionPerformed(evt);
            }
        });
        panel_AllBooks.add(btn_select6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 110, 40));

        txt_priceBook6.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_priceBook6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_priceBook6.setText("ราคา :");
        panel_AllBooks.add(txt_priceBook6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 150, 30));

        txt_nameBook6.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_nameBook6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nameBook6.setText("ชื่อหนังสือ");
        panel_AllBooks.add(txt_nameBook6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 150, 30));

        lbl_showBook6.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lbl_showBook6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showBook6.setText("ปกหนังสือที่ 6");
        panel_AllBooks.add(lbl_showBook6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 150, 210));

        lbl_showBook7.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lbl_showBook7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showBook7.setText("ปกหนังสือที่ 7");
        panel_AllBooks.add(lbl_showBook7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 150, 210));

        txt_nameBook7.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_nameBook7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nameBook7.setText("ชื่อหนังสือ");
        panel_AllBooks.add(txt_nameBook7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 620, 150, 30));

        txt_priceBook7.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_priceBook7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_priceBook7.setText("ราคา :");
        panel_AllBooks.add(txt_priceBook7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 660, 150, 30));

        btn_select7.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_select7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_browse.png"))); // NOI18N
        btn_select7.setText("เลือกดู");
        btn_select7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select7ActionPerformed(evt);
            }
        });
        panel_AllBooks.add(btn_select7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 700, 110, 40));

        btn_select8.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_select8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_browse.png"))); // NOI18N
        btn_select8.setText("เลือกดู");
        btn_select8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select8ActionPerformed(evt);
            }
        });
        panel_AllBooks.add(btn_select8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 700, 110, 40));

        txt_priceBook8.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_priceBook8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_priceBook8.setText("ราคา :");
        panel_AllBooks.add(txt_priceBook8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 660, 150, 30));

        txt_nameBook8.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_nameBook8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nameBook8.setText("ชื่อหนังสือ");
        panel_AllBooks.add(txt_nameBook8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 150, 30));

        lbl_showBook8.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lbl_showBook8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showBook8.setText("ปกหนังสือที่ 8");
        panel_AllBooks.add(lbl_showBook8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, 150, 210));

        lbl_showBook9.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lbl_showBook9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showBook9.setText("ปกหนังสือที่ 9");
        panel_AllBooks.add(lbl_showBook9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 150, 210));

        lbl_showBook10.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lbl_showBook10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_showBook10.setText("ปกหนังสือที่ 10");
        panel_AllBooks.add(lbl_showBook10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 150, 210));

        txt_nameBook9.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_nameBook9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nameBook9.setText("ชื่อหนังสือ");
        panel_AllBooks.add(txt_nameBook9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 620, 150, 30));

        txt_nameBook10.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_nameBook10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_nameBook10.setText("ชื่อหนังสือ");
        panel_AllBooks.add(txt_nameBook10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 620, 150, 30));

        txt_priceBook10.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_priceBook10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_priceBook10.setText("ราคา :");
        panel_AllBooks.add(txt_priceBook10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 660, 150, 30));

        txt_priceBook9.setFont(new java.awt.Font("Ekkamai Standard", 0, 12)); // NOI18N
        txt_priceBook9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_priceBook9.setText("ราคา :");
        panel_AllBooks.add(txt_priceBook9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 660, 150, 30));

        btn_select9.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_select9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_browse.png"))); // NOI18N
        btn_select9.setText("เลือกดู");
        btn_select9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select9ActionPerformed(evt);
            }
        });
        panel_AllBooks.add(btn_select9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 700, 110, 40));

        btn_select10.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        btn_select10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_browse.png"))); // NOI18N
        btn_select10.setText("เลือกดู");
        btn_select10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_select10ActionPerformed(evt);
            }
        });
        panel_AllBooks.add(btn_select10, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 700, 110, 40));

        jScrollPane2.setViewportView(panel_AllBooks);

        panelBookAll.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 900, 350));

        lbl_AllBooks.setFont(new java.awt.Font("Ekkamai Standard", 1, 24)); // NOI18N
        lbl_AllBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_allbook_50px.png"))); // NOI18N
        lbl_AllBooks.setText("หนังสือทั้งหมด");
        panelBookAll.add(lbl_AllBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 220, 50));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_back.png"))); // NOI18N
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        panelBookAll.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, -1, -1));

        btn_next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/img_nextbutton.png"))); // NOI18N
        btn_next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_nextMouseClicked(evt);
            }
        });
        panelBookAll.add(btn_next, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 530, -1, -1));

        add(panelBookAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_search1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_search1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_search1MouseClicked

    private void btn_showListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_showListActionPerformed

    private void btn_select1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select1ActionPerformed
        // TODO add your handling code here:
        Bookstore form = new Bookstore();
       Main.setFrame(form); 
//        form.setBook(txt_nameBook1.getText());
    }//GEN-LAST:event_btn_select1ActionPerformed

    private void btn_select2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select2ActionPerformed
        // TODO add your handling code here:
        Bookstore form = new Bookstore();
         Main.setFrame(form); 
//        form.setBook(txt_nameBook1.getText());
    }//GEN-LAST:event_btn_select2ActionPerformed

    private void btn_select3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select3ActionPerformed
        // TODO add your handling code here:
        Bookstore form = new Bookstore();
        Main.setFrame(form); 
//        form.setBook(txt_nameBook1.getText());
    }//GEN-LAST:event_btn_select3ActionPerformed

    private void btn_select4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select4ActionPerformed
        // TODO add your handling code here:
        Bookstore form = new Bookstore();
        Main.setFrame(form); 
//        form.setBook(txt_nameBook1.getText());
    }//GEN-LAST:event_btn_select4ActionPerformed

    private void btn_select5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select5ActionPerformed
        // TODO add your handling code here:
        Bookstore form = new Bookstore();
         Main.setFrame(form);  
//        form.setBook(txt_nameBook1.getText());
    }//GEN-LAST:event_btn_select5ActionPerformed

    private void btn_select6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select6ActionPerformed
        Bookstore form = new Bookstore();
         Main.setFrame(form); 
//        form.setBook(txt_nameBook1.getText());
    }//GEN-LAST:event_btn_select6ActionPerformed

    private void btn_select7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select7ActionPerformed
        // TODO add your handling code here:
        Bookstore form = new Bookstore();
         Main.setFrame(form); 
//        form.setBook(txt_nameBook1.getText());
    }//GEN-LAST:event_btn_select7ActionPerformed

    private void btn_select8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select8ActionPerformed
        // TODO add your handling code here:
        Bookstore form = new Bookstore();
         Main.setFrame(form); 
//        form.setBook(txt_nameBook1.getText());
        
    }//GEN-LAST:event_btn_select8ActionPerformed

    private void btn_select9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select9ActionPerformed
        // TODO add your handling code here:
        Bookstore form = new Bookstore();
         Main.setFrame(form); 
//        form.setBook(txt_nameBook1.getText());
        
    }//GEN-LAST:event_btn_select9ActionPerformed

    private void btn_select10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_select10ActionPerformed
        // TODO add your handling code here:
        Bookstore form = new Bookstore();
         Main.setFrame(form);  
//        form.setBook(txt_nameBook1.getText());
        
    }//GEN-LAST:event_btn_select10ActionPerformed

    private void btn_nextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_nextMouseClicked
        // TODO add your handling code here:
        //        setAllBook();
    }//GEN-LAST:event_btn_nextMouseClicked

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        // TODO add your handling code here:
        //        setAllBook();
    }//GEN-LAST:event_btn_backMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_allBooks;
    private javax.swing.JLabel btn_back;
    private javax.swing.JButton btn_basket1;
    private javax.swing.JButton btn_editbook1;
    private javax.swing.JButton btn_home1;
    private javax.swing.JButton btn_loginStatus1;
    private javax.swing.JPanel btn_menubar1;
    private javax.swing.JLabel btn_next;
    private javax.swing.JTextField btn_search1;
    private javax.swing.JButton btn_search_icon1;
    private javax.swing.JButton btn_select1;
    private javax.swing.JButton btn_select10;
    private javax.swing.JButton btn_select2;
    private javax.swing.JButton btn_select3;
    private javax.swing.JButton btn_select4;
    private javax.swing.JButton btn_select5;
    private javax.swing.JButton btn_select6;
    private javax.swing.JButton btn_select7;
    private javax.swing.JButton btn_select8;
    private javax.swing.JButton btn_select9;
    private javax.swing.JButton btn_showList;
    private javax.swing.JLabel btn_userStatus1;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel img_customercare1;
    private javax.swing.JLabel img_logo1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_AllBooks;
    private javax.swing.JPanel lbl_bookdetail;
    private javax.swing.JLabel lbl_showBook1;
    private javax.swing.JLabel lbl_showBook10;
    private javax.swing.JLabel lbl_showBook2;
    private javax.swing.JLabel lbl_showBook3;
    private javax.swing.JLabel lbl_showBook4;
    private javax.swing.JLabel lbl_showBook5;
    private javax.swing.JLabel lbl_showBook6;
    private javax.swing.JLabel lbl_showBook7;
    private javax.swing.JLabel lbl_showBook8;
    private javax.swing.JLabel lbl_showBook9;
    private javax.swing.JLabel lbl_statusbar1;
    private javax.swing.JLabel lbl_version1;
    private javax.swing.JPanel panelBookAll;
    private javax.swing.JPanel panelMenu1;
    private javax.swing.JPanel panel_AllBooks;
    private javax.swing.JPanel statusbar1;
    private javax.swing.JLabel txt_nameBook1;
    private javax.swing.JLabel txt_nameBook10;
    private javax.swing.JLabel txt_nameBook2;
    private javax.swing.JLabel txt_nameBook3;
    private javax.swing.JLabel txt_nameBook4;
    private javax.swing.JLabel txt_nameBook5;
    private javax.swing.JLabel txt_nameBook6;
    private javax.swing.JLabel txt_nameBook7;
    private javax.swing.JLabel txt_nameBook8;
    private javax.swing.JLabel txt_nameBook9;
    private javax.swing.JLabel txt_priceBook1;
    private javax.swing.JLabel txt_priceBook10;
    private javax.swing.JLabel txt_priceBook2;
    private javax.swing.JLabel txt_priceBook3;
    private javax.swing.JLabel txt_priceBook4;
    private javax.swing.JLabel txt_priceBook5;
    private javax.swing.JLabel txt_priceBook6;
    private javax.swing.JLabel txt_priceBook7;
    private javax.swing.JLabel txt_priceBook8;
    private javax.swing.JLabel txt_priceBook9;
    // End of variables declaration//GEN-END:variables
}
