/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author I3
 */
public class DetailBook extends javax.swing.JPanel {

   

    /**
     * Creates new form BookStore
     */
    public DetailBook() {
        initComponents();
        
    }
    
 public  void showBook(String name){
     
     Books book = DetailBookService.getBook(name);
     if(book!=null){
     lblBookName.setText("ชื่อ "+book.bookname);
     lblAuthorName.setText("ผู้แต่ง "+book.author);
     lblBookType.setText("ประเภท "+book.booktype);
     lblBookPrice.setText("ราคา "+Double.toString(book.bookprice));
     lblBookPublisher.setText("สำนักพิมพ์ "+book.publisher);
     lblBookYears.setText("ปี "+Integer.toString(book.year));
     lblBookLanguage.setText("ภาษา "+book.language);
     lblBookPageNumber.setText("จำนวนหน้า "+Integer.toString(book.countpage)); 
     
      try{
         BufferedImage imgBuffer = BookDAO.getImageBook(book.bookname);
         Image rescale = imgBuffer.getScaledInstance(280, 390, Image.SCALE_DEFAULT);  
         imgShowBook.setIcon(new ImageIcon(rescale));
         }catch (IOException ex) {
           
        }
     }     
     
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBook = new javax.swing.JPanel();
        imgShowBook = new javax.swing.JLabel();
        btnSelectCount = new javax.swing.JSpinner();
        btnPick = new javax.swing.JButton();
        lblBookName = new javax.swing.JLabel();
        lblAuthorName = new javax.swing.JLabel();
        lblBookType = new javax.swing.JLabel();
        lblBookPrice = new javax.swing.JLabel();
        lblBookPublisher = new javax.swing.JLabel();
        lblBookYears = new javax.swing.JLabel();
        lblBookLanguage = new javax.swing.JLabel();
        lblBookPageNumber = new javax.swing.JLabel();
        lblShowDetail = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        lblUserStatus = new javax.swing.JLabel();
        lblMenuBar = new javax.swing.JPanel();
        btnAllBook = new javax.swing.JButton();
        btnCart = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        imgCusCare = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBook.setBackground(new java.awt.Color(255, 255, 255));
        panelBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgShowBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgShowBook.setText("รูป");
        panelBook.add(imgShowBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 280, 390));

        btnSelectCount.setFont(new java.awt.Font("Ekkamai Standard", 1, 24)); // NOI18N
        btnSelectCount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        btnSelectCount.setVerifyInputWhenFocusTarget(false);
        panelBook.add(btnSelectCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 110, 40));

        btnPick.setBackground(new java.awt.Color(204, 204, 255));
        btnPick.setFont(new java.awt.Font("Ekkamai Standard", 1, 14)); // NOI18N
        btnPick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgShoppingCart.png"))); // NOI18N
        btnPick.setText("หยิบใส่ตะกร้า");
        btnPick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPickActionPerformed(evt);
            }
        });
        panelBook.add(btnPick, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 160, 40));

        lblBookName.setFont(new java.awt.Font("Ekkamai Standard", 1, 18)); // NOI18N
        lblBookName.setText("ชื่อ");
        panelBook.add(lblBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 410, 60));

        lblAuthorName.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        lblAuthorName.setText("ผู้แต่ง");
        panelBook.add(lblAuthorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 390, 60));

        lblBookType.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        lblBookType.setText("ประเภท");
        panelBook.add(lblBookType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 390, 60));

        lblBookPrice.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        lblBookPrice.setText("1");
        panelBook.add(lblBookPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 390, 60));

        lblBookPublisher.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        lblBookPublisher.setText("สำนักพิมพ์");
        panelBook.add(lblBookPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 390, 60));

        lblBookYears.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        lblBookYears.setText("ปี");
        panelBook.add(lblBookYears, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 390, 60));

        lblBookLanguage.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        lblBookLanguage.setText("ภาษา");
        panelBook.add(lblBookLanguage, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 390, 60));

        lblBookPageNumber.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        lblBookPageNumber.setText("หน้า");
        panelBook.add(lblBookPageNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 390, 60));

        lblShowDetail.setBackground(new java.awt.Color(233, 233, 255));
        panelBook.add(lblShowDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 460, 360));

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setName(""); // NOI18N
        panelMenu.setPreferredSize(new java.awt.Dimension(1024, 60));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUserStatus.setBackground(new java.awt.Color(255, 255, 255));
        lblUserStatus.setFont(new java.awt.Font("Ekkamai Standard", 1, 18)); // NOI18N
        lblUserStatus.setForeground(new java.awt.Color(204, 204, 255));
        lblUserStatus.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUserStatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgUser.png"))); // NOI18N
        lblUserStatus.setText("mamafakka");
        panelMenu.add(lblUserStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 220, 40));

        lblMenuBar.setBackground(new java.awt.Color(204, 204, 255));
        lblMenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAllBook.setBackground(new java.awt.Color(204, 204, 255));
        btnAllBook.setFont(new java.awt.Font("Ekkamai Standard", 0, 17)); // NOI18N
        btnAllBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgAllbook1.png"))); // NOI18N
        btnAllBook.setText("หนังสือทั้งหมด");
        btnAllBook.setBorder(null);
        btnAllBook.setBorderPainted(false);
        btnAllBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAllBook.setFocusable(false);
        btnAllBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllBookActionPerformed(evt);
            }
        });
        lblMenuBar.add(btnAllBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 160, 40));

        btnCart.setBackground(new java.awt.Color(204, 204, 255));
        btnCart.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        btnCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgShoppingCart.png"))); // NOI18N
        btnCart.setBorder(null);
        btnCart.setBorderPainted(false);
        btnCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCart.setFocusable(false);
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });
        lblMenuBar.add(btnCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 80, 40));

        panelMenu.add(lblMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1080, 40));

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgLogo2.png"))); // NOI18N
        panelMenu.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 270, 60));

        imgCusCare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgContact.png"))); // NOI18N
        panelMenu.add(imgCusCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 230, 60));

        panelBook.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 99));

        add(panelBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPickActionPerformed
        String[] partsName = lblBookName.getText().split(" ");
        String nameBook = partsName[1]; 
        String[] partsPrice = lblBookPrice.getText().split(" ");
        double priceBook = Double.parseDouble(partsPrice[1]); 
        if(DetailBookService.orderCart==null){
        DetailBookService.newOrder();
        }
        DetailBookService.addOrder(nameBook, priceBook,
                (Integer)btnSelectCount.getValue());
      JOptionPane.showMessageDialog(this, "ใส่ตะกร้าแล้ว");
    }//GEN-LAST:event_btnPickActionPerformed

    private void btnAllBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllBookActionPerformed
        // TODO add your handling code here:
         DetailBookService.toAllBook();
    }//GEN-LAST:event_btnAllBookActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        DetailBookService.toDetailOrder();
        
    }//GEN-LAST:event_btnCartActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllBook;
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnPick;
    private javax.swing.JSpinner btnSelectCount;
    private javax.swing.JLabel imgCusCare;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgShowBook;
    private javax.swing.JLabel lblAuthorName;
    private javax.swing.JLabel lblBookLanguage;
    private javax.swing.JLabel lblBookName;
    private javax.swing.JLabel lblBookPageNumber;
    private javax.swing.JLabel lblBookPrice;
    private javax.swing.JLabel lblBookPublisher;
    private javax.swing.JLabel lblBookType;
    private javax.swing.JLabel lblBookYears;
    private javax.swing.JPanel lblMenuBar;
    private javax.swing.JPanel lblShowDetail;
    private javax.swing.JLabel lblUserStatus;
    private javax.swing.JPanel panelBook;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables

    
}
