/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static myapp.DetailBookService.orderCart;
import static myapp.DetailBookService.orderList;

/**
 *
 * @author I3
 */
public class DetailOrder extends javax.swing.JPanel {

    /**
     * Creates new form BookStore
     */
    
    public DetailOrder() {
        initComponents();
        
       
        
    }
    static OrderCart orderCart;

   
 public void showOrderDetail(OrderCart orderCart){
      this.orderCart=orderCart;
      String[] columnNames = {"ชื่อ","จำนวน"};
            DefaultTableModel column = new DefaultTableModel(columnNames, 0);
          if(orderCart!=null){
            for(Orders list:orderCart.orders)   {
              column.addRow(new Object[] {list.bookname,list.bookamount});
              
          }
          }
          tblShowListBooks.setModel(column);
          txtPrice.setText(Double.toString(orderCart.totalPrice));
          
       tblShowListBooks.setDefaultEditor(Object.class, null);
       DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tblShowListBooks.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        
  }
     
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBook = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblMenuBar = new javax.swing.JPanel();
        btnAllBook = new javax.swing.JButton();
        btnCart = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        imgCusCare = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowListBooks = new javax.swing.JTable();
        txtCredit = new javax.swing.JTextField();
        lblCredit = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblBaht = new javax.swing.JLabel();
        btnFinish = new javax.swing.JButton();
        lblOrderList = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBook.setBackground(new java.awt.Color(255, 255, 255));
        panelBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setName(""); // NOI18N
        panelMenu.setPreferredSize(new java.awt.Dimension(1024, 60));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setBackground(new java.awt.Color(255, 255, 255));
        lblUsername.setFont(new java.awt.Font("Ekkamai Standard", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(204, 204, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgUser.png"))); // NOI18N
        lblUsername.setText("mamafakka");
        panelMenu.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 230, 40));

        lblMenuBar.setBackground(new java.awt.Color(204, 204, 255));
        lblMenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAllBook.setBackground(new java.awt.Color(204, 204, 255));
        btnAllBook.setFont(new java.awt.Font("Ekkamai Standard", 0, 17)); // NOI18N
        btnAllBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgAllbook1.png"))); // NOI18N
        btnAllBook.setText("หนังสือทั้งหมด");
        btnAllBook.setBorder(null);
        btnAllBook.setBorderPainted(false);
        btnAllBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAllBook.setFocusable(false);
        btnAllBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllBookActionPerformed(evt);
            }
        });
        lblMenuBar.add(btnAllBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 160, 40));

        btnCart.setBackground(new java.awt.Color(204, 204, 255));
        btnCart.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        btnCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgShoppingCart.png"))); // NOI18N
        btnCart.setBorder(null);
        btnCart.setBorderPainted(false);
        btnCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCart.setFocusable(false);
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });
        lblMenuBar.add(btnCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 80, 40));

        panelMenu.add(lblMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1080, 40));

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgLogo2.png"))); // NOI18N
        panelMenu.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 270, 60));

        imgCusCare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgContact.png"))); // NOI18N
        panelMenu.add(imgCusCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 230, 60));

        panelBook.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 99));

        tblShowListBooks.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        tblShowListBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblShowListBooks);

        panelBook.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 590, 290));
        panelBook.add(txtCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 310, 30));

        lblCredit.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        lblCredit.setText("กรอกเลขบัตรเครดิตเพื่อทำการชำระเงิน");
        panelBook.add(lblCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 310, 40));

        lblPrice.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrice.setText("ราคาสุทธิ");
        panelBook.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 70, 30));

        txtPrice.setEditable(false);
        txtPrice.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        panelBook.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 120, 30));

        lblBaht.setFont(new java.awt.Font("Ekkamai Standard", 0, 14)); // NOI18N
        lblBaht.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBaht.setText("บาท");
        panelBook.add(lblBaht, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 30, 30));

        btnFinish.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        btnFinish.setText("เสร็จสิ้น");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });
        panelBook.add(btnFinish, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 530, -1, -1));

        lblOrderList.setFont(new java.awt.Font("Ekkamai Standard", 0, 20)); // NOI18N
        lblOrderList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderList.setText("สรุปรายการสั่งซื้อ");
        panelBook.add(lblOrderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 114, 590, 30));

        add(panelBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        // TODO add your handling code here:
        if(this.orderCart.totalPrice!=0 && !txtCredit.getText().isEmpty()){
        DetailOrderService.saveToDataBase(txtCredit.getText(),this.orderCart);
        DetailOrderService.toRecipt();
        txtPrice.setText("");
        orderCart.orders.clear();
        orderCart.totalPrice=0;
        }else{
            JOptionPane.showMessageDialog(this, "กรุณากรอกข้อมูลให้ครบก่อนสั่งซื้อ");
        }
    }//GEN-LAST:event_btnFinishActionPerformed

    private void btnAllBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllBookActionPerformed
        // TODO add your handling code here:
        DetailBookService.toAllBook();
    }//GEN-LAST:event_btnAllBookActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllBook;
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnFinish;
    private javax.swing.JLabel imgCusCare;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBaht;
    private javax.swing.JLabel lblCredit;
    private javax.swing.JPanel lblMenuBar;
    private javax.swing.JLabel lblOrderList;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelBook;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTable tblShowListBooks;
    private javax.swing.JTextField txtCredit;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
