/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static myapp.DetailOrder.orderCart;

/**
 *
 * @author I3
 */
public class Receipt extends javax.swing.JPanel {

    /**
     * Creates new form BookStore
     */
    public Receipt() {
        initComponents();
        showReceipt();
        
    }
    
    public void showReceipt(){
        OrderCart orderCart = ReceiptService.getOrderLastest();
        lblIdBill.setText(Integer.toString(orderCart.orderID));
        String[] columnNames = {"ชื่อ","จำนวน"};
            DefaultTableModel column = new DefaultTableModel(columnNames, 0);
          if(orderCart!=null){
            for(Orders list:orderCart.orders)   {
              column.addRow(new Object[] {list.bookname,list.bookamount});
              
          } 
          
          }
          tblShowReceiptOrderList.setModel(column);
         txtTotal.setText(Double.toString(orderCart.totalPrice));
          
       tblShowReceiptOrderList.setDefaultEditor(Object.class, null);
       DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tblShowReceiptOrderList.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        
  }
        
    
     
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBook = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblMenuBar = new javax.swing.JPanel();
        btnAllBook = new javax.swing.JButton();
        imgLogo = new javax.swing.JLabel();
        imgCusCare = new javax.swing.JLabel();
        lblOrder = new javax.swing.JLabel();
        lblIdBill = new javax.swing.JLabel();
        lblReceipt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowReceiptOrderList = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        lblBath = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBook.setBackground(new java.awt.Color(255, 255, 255));
        panelBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setName(""); // NOI18N
        panelMenu.setPreferredSize(new java.awt.Dimension(1024, 60));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setBackground(new java.awt.Color(255, 255, 255));
        lblUsername.setFont(new java.awt.Font("Ekkamai Standard", 1, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(204, 204, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgUser.png"))); // NOI18N
        lblUsername.setText("mamafakka");
        panelMenu.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 220, 40));

        lblMenuBar.setBackground(new java.awt.Color(204, 204, 255));
        lblMenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAllBook.setBackground(new java.awt.Color(204, 204, 255));
        btnAllBook.setFont(new java.awt.Font("Ekkamai Standard", 0, 17)); // NOI18N
        btnAllBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgAllbook1.png"))); // NOI18N
        btnAllBook.setText("หนังสือทั้งหมด");
        btnAllBook.setBorder(null);
        btnAllBook.setBorderPainted(false);
        btnAllBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAllBook.setFocusable(false);
        btnAllBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllBookActionPerformed(evt);
            }
        });
        lblMenuBar.add(btnAllBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 160, 40));

        panelMenu.add(lblMenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 60, 1080, 40));

        imgLogo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgLogo2.png"))); // NOI18N
        panelMenu.add(imgLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 270, 60));

        imgCusCare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/java/myapp/images/imgContact.png"))); // NOI18N
        panelMenu.add(imgCusCare, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 230, 60));

        panelBook.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 99));

        lblOrder.setFont(new java.awt.Font("Ekkamai Standard", 0, 18)); // NOI18N
        lblOrder.setText("Order #");
        panelBook.add(lblOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, 40));

        lblIdBill.setFont(new java.awt.Font("Ekkamai Standard", 0, 18)); // NOI18N
        lblIdBill.setText("ID bill");
        panelBook.add(lblIdBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 130, 40));

        lblReceipt.setFont(new java.awt.Font("Ekkamai Standard", 0, 24)); // NOI18N
        lblReceipt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReceipt.setText("ใบเสร็จ");
        panelBook.add(lblReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 650, -1));

        tblShowReceiptOrderList.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        tblShowReceiptOrderList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblShowReceiptOrderList.setGridColor(new java.awt.Color(255, 255, 255));
        tblShowReceiptOrderList.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tblShowReceiptOrderList);

        panelBook.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 650, 300));

        lblTotal.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("ราคารวม");
        panelBook.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 90, 30));

        lblBath.setFont(new java.awt.Font("Ekkamai Standard", 0, 18)); // NOI18N
        lblBath.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBath.setText("บาท");
        panelBook.add(lblBath, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 60, -1));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Ekkamai Standard", 0, 16)); // NOI18N
        panelBook.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 250, -1));

        add(panelBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAllBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllBookActionPerformed
        // TODO add your handling code here:
        ReceiptService.toAllBook();
    }//GEN-LAST:event_btnAllBookActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllBook;
    private javax.swing.JLabel imgCusCare;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBath;
    private javax.swing.JLabel lblIdBill;
    private javax.swing.JPanel lblMenuBar;
    private javax.swing.JLabel lblOrder;
    private javax.swing.JLabel lblReceipt;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel panelBook;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTable tblShowReceiptOrderList;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
